consumption <- read.csv2("household_power_consumption.txt", na.strings = "?", as.is = TRUE)
data <- subset(consumption, Date == '1/2/2007'|Date == '2/2/2007', select = c("Date", "Time", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
temp <- paste(data$Date, data$Time)
time <- strptime(temp, "%d/%m/%Y %H:%M:%S")
Sys.setlocale(category="LC_TIME",local="USA")
par(mfcol = c(1,1))
plot(time, data$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = "")
lines(time, data$Sub_metering_2, col = "red")
lines(time, data$Sub_metering_3, col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black","red","blue"), lty = 1)
dev.copy(png, file="plot3.png")
dev.off()