consumption <- read.csv2("household_power_consumption.txt", na.strings = "?", as.is = TRUE)
data <- subset(consumption, Date == '1/2/2007'|Date == '2/2/2007')
temp <- paste(data$Date, data$Time)
datetime <- strptime(temp, "%d/%m/%Y %H:%M:%S")
Sys.setlocale(category="LC_TIME",local="USA")
par(mfcol = c(2,2), mar=c(4,4,1,2))
plot(datetime, data$Global_active_power,type = "l", ylab = "Global Active Power", xlab = "")
plot(datetime, data$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = "")
lines(datetime, data$Sub_metering_2, col = "red")
lines(datetime, data$Sub_metering_3, col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black","red","blue"), lty = 1, bty = "n", cex = 0.7)
plot(datetime, data$Voltage, type = "l", ylab = "Voltage")
plot(datetime, data$Global_reactive_power, type = "l", ylab = "Global_reactive_power")
dev.copy(png, file = "plot4.png")
dev.off()