consumption <- read.csv2("household_power_consumption.txt", na.strings = "?", as.is = TRUE)
data <- subset(consumption, Date == '1/2/2007'|Date == '2/2/2007', select = Date:Global_active_power)
temp <- paste(data$Date, data$Time)
time <- strptime(temp, "%d/%m/%Y %H:%M:%S")
Sys.setlocale(category="LC_TIME",local="USA")
par(mfcol = c(1,1))
plot(time, data$Global_active_power,type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
dev.copy(png, file = "plot2.png")
dev.off()